name: Sync to Repereetta

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Repereetta
        run: |
          git remote add target https://x-access-token:${{ secrets.REPO_B_TOKEN }}@github.com/Repereetta/github-data-weaver.git
          
          git push target HEAD:main --force
